#
# Makefile for the Bytedance module
#

obj-$(CONFIG_BYTEDANCE_HOOKBIND) += hookbind/
obj-$(CONFIG_BYTEDANCE_BLACKHOLEFS) += blackholefs/
obj-$(CONFIG_BYTEDANCE_SMITH) += smith/
obj-$(CONFIG_BYTEDANCE_TRACE_IRQOFF) += trace_irqoff.o
obj-$(CONFIG_BYTEDANCE_HOT_INSPECTOR) += hot_inspector.o
obj-$(CONFIG_BYTEDANCE_TOA) += toa.o
