# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2024, ByteDance Ltd. and/or its affiliates. All rights reserved.
#
# Makefile for hook bind module
#
obj-$(CONFIG_BYTEDANCE_HOOKBIND) += hookbind.o
hookbind-y := hookbind_sys.o hookbind_char.o

