# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2024, ByteDance Ltd. and/or its affiliates. All rights reserved.
#
# Makefile for blackholefs module
#
obj-$(CONFIG_BYTEDANCE_BLACKHOLEFS) += blackholefs.o
blackholefs-y := file.o inode.o
