# SPDX-License-Identifier: GPL-2.0
#
# Makefile for cpuinspect.
#
obj-$(CONFIG_CPU_INSPECT) += cpu_inspect.o
obj-$(CONFIG_CPU_INSPECTOR_ATF) += inspector-atf.o
cpu_inspect-y = cpuinspect.o inspector.o sysfs.o
